/* GENERATED by scripts/sync-api-version.mjs - do not edit by hand (npm run sync:api-version).
   The fingerprint of lib/prompts.js + lib/sizing.js. The Worker sends it with every /size and
   /prompt answer (X-Pear-Api) and the room accepts an edge answer only when it matches the one it
   was built with - see the script's header. */
export const API_VERSION = "52a862a04f9249dc";
